# Copyright (c) 2025-2026 Andrea Ballestrazzi
name: Windows x64 MSVC Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: [Release, Debug]
    steps:
      - uses: actions/checkout@v6

      - name: Configure
        run: cmake -B build -DVERSO_BUILD_TESTS=ON -DVERSO_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ matrix['build-type'] }}

      - name: Build all targets
        run: cmake --build build --config ${{ matrix['build-type'] }} -- /m

      - name: Run tests
        run: |
          .\build\tests\${{ matrix['build-type'] }}\verso-tests.exe -S
